spring:
  profile:
    active:
      - dev
---
server:
  port: 7001

eureka:
  instance:
    hostname: eureka1
  server:
    eviction-interval-timer-in-ms: 1000 #设置清理的间隔时间，而且这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:lisl@eureka1:7001/eureka,http://admin:lisl@eureka2:7002/eureka,http://admin:lisl@eureka3:7003/eureka
spring:
  security:
    user:
      name: admin
      password: lisl
  profile: dev

---
server:
  port: 7002

eureka:
  instance:
    hostname: eureka1
  server:
    eviction-interval-timer-in-ms: 1000 #设置清理的间隔时间，而且这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:lisl@eureka1:7001/eureka,http://admin:lisl@eureka2:7002/eureka,http://admin:lisl@eureka3:7003/eureka
spring:
  security:
    user:
      name: admin
      password: lisl
  profile: beta